language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

services:
  - memcached

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - travis_retry composer install -n

script: vendor/bin/phpunit
